spring:
  application:
    name: wigell_mc_rental

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wigell_mc_db?createDatabaseIfNotExist=true
    username: root
    password: root

  sql:
    init:
      mode: always

  boot:
    admin:
      client:
        url: http://localhost:8084/
        username: admin
        password: password
        instance:
          service-url: http://localhost:8585/

server:
  port: 8585

logging:
  level:
    root: INFO
    com.sjoqvist.wigell_mc_rental: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true